apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  labels:
    app: nginx-node-selector
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
  nodeSelector:
    kind: "worker1"