apiVersion: v1
kind: Pod
metadata:
  name: pod-multi-container
  labels:
    app: pod-multi-container
spec:
  containers:

    # REMEMBER THIS
    # Pod will Error / Pending / NotReady if one of the container are
    # COMPLETED, ERROR, EXIT (There is no process inside of one of the containers)
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    
    # Once this reach 10 secode, POD will restart again
    # because sleep 10 has been reached
    - name: busybox
      image: busybox
      args:
        - "sleep"
        - "100"