apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-resources
  labels:
    app: nginx-with-resources
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: 2
          memory: 512Mi
        limits:
          cpu: 3
          memory: 1Gi