# Run taint-node.sh (for taint the node ss-sql-cluster-worker, demo purposes)

# Since there is no NodeName specified,
# And also there are no tolerations of pod
# There will be no pod will schedule on node ss-sql-cluster-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-with-toleration
  labels:
    app: nginx-deployment-with-toleration
    tier: frontend
spec:
  template:
    metadata:
      name: nginx-deployment-with-toleration
      labels:
        name: nginx-deployment-with-toleration
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      name: nginx-deployment-with-toleration
  replicas: 15