apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual
  labels:
    app: nginx-manual
    tier: frontend
spec:
  containers:
    - name: nginx
      image: nginx
  # this is for assigning pod to node (define manually scheduling)
  nodeName: ss-sql-cluster-worker