apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    app: nginx-daemonset
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx-daemonset
  template:
    metadata:
      name: nginx-daemonset
      labels:
        app: nginx-daemonset
    spec:
      containers:
        - name: nginx
          image: nginx