apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # you can encode and decode using this
  # encode -> echo 'mypass123' | base64
  # decode -> echo 'bXlwYXNzMTIzCg==' | base64 --decode
  INJECT_SECRET_TO_POD: bXlwYXNzMTIzCg==
